---
  server:
    authtype: basic
    basicauth:
      username: admin
      password: admin

  cloudfoundries:
    cf-eu10:
      apiURL: "https://api.cf.eu10.hana.ondemand.com"
      uaaURL: "https://uaa.cf.eu10.hana.ondemand.com"
      username: admin
      password: admin
      labels:
      - master
      - aws
    cf-eu10-001:
      apiURL: "https://api.cf.eu10-001.hana.ondemand.com"
      uaaURL: "https://uaa.cf.eu10-001.hana.ondemand.com"
      username: admin
      password: admin
      labels:
      - scaleout
      - aws
    cf-eu10-002:
      apiURL: "https://api.cf.eu10-002.hana.ondemand.com"
      uaaURL: "https://uaa.cf.eu10-002.hana.ondemand.com"
      username: admin
      password: admin
      labels:
      - scaleout
      - aws
